# Generated by Django 4.2.7 on 2023-11-16 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_board', models.CharField(max_length=200)),
                ('destination_board', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('list_type', models.CharField(choices=[('IDEAS', 'Ideas'), ('TODO', 'Todo'), ('DOING', 'Doing'), ('DONE', 'Done')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='donelist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='ideaslist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoingList',
        ),
        migrations.DeleteModel(
            name='DoneList',
        ),
        migrations.DeleteModel(
            name='IdeasList',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
        migrations.AddField(
            model_name='boardlist',
            name='items',
            field=models.ManyToManyField(related_name='boardlist', to='items.item'),
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
