# Generated by Django 4.2.7 on 2023-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_activity_boardlist_remove_donelist_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('MOVED', 'Moved'), ('DELETED', 'Deleted')], default='CREATED', max_length=7),
        ),
    ]
