# Generated by Django 4.2.7 on 2023-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='display_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
