# Generated by Django 4.2.7 on 2023-12-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_display_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_date',
        ),
    ]
