# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_item_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item'),
        ),
    ]
