# Generated by Django 4.2.7 on 2023-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_activity_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
