# Generated by Django 4.2.7 on 2023-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_activity_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='item_content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
