# Generated by Django 4.2.7 on 2023-12-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_activity_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item'),
        ),
    ]
