# Generated by Django 4.2.7 on 2023-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_activity_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='item_content',
        ),
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
