# Generated by Django 4.2.7 on 2023-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_activity_item_content_item_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
